#!/usr/bin/env node
/**
 * setup_env.js
 * ─────────────
 * Reads .env.example and writes a populated .env file with all live
 * production contract addresses pre-filled. Placeholder values that
 * require user input are left empty with inline comments.
 *
 * Usage:  node scripts/setup_env.js
 */
import { writeFileSync, existsSync, readFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const ENV_PATH = resolve(ROOT, ".env");

// ─── Live Production Addresses ─────────────────────────────────────────────
// Hub Chain: Creditcoin Testnet (Chain ID: 102031)
const LIVE = {
    GYE_MANAGER_ADDRESS: "0xC6AF175200807DeE213f58D4C375a574284ba2f0",
    BIDDING_ENGINE_ADDRESS: "0xa513E6E4b8f2a923D98304ec87F64353C4D5C853",
    SCORE_MANAGER_ADDRESS: "0x0165878A594ca255338adfa4d48449f69242Eb8F",
    GYE_STAKING_ADDRESS: "0x60CeeEb9A7172Fd20339692B19e0228087e17AA9",
    MOIGYE_SBT_ADDRESS: "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D",
    MOIGYE_USD_ADDRESS: "0x4ed7c06655c1b138c84014c119902c0039725807",
};

// ─── Generated .env content ────────────────────────────────────────────────
const ENV_CONTENT = `# ═══════════════════════════════════════════════════════════════
# Moigye Protocol — Environment Config
# Auto-generated by scripts/setup_env.js on ${new Date().toISOString()}
# ═══════════════════════════════════════════════════════════════

# ── Wallet ────────────────────────────────────────────────────
# REQUIRED: Your deployer/signer private key (with leading 0x)
PRIVATE_KEY=""

# ── RPC Endpoints ─────────────────────────────────────────────
# Sepolia RPC (Alchemy, Infura, or public endpoint)
SEPOLIA_RPC_URL=""
# Creditcoin Testnet RPC (pre-configured — change only if needed)
CTC_RPC_URL=https://rpc.cc3-testnet.creditcoin.network

# ── Hub Chain Contracts (Creditcoin Testnet — Chain ID: 102031) ─
GYE_MANAGER_ADDRESS=${LIVE.GYE_MANAGER_ADDRESS}
BIDDING_ENGINE_ADDRESS=${LIVE.BIDDING_ENGINE_ADDRESS}
SCORE_MANAGER_ADDRESS=${LIVE.SCORE_MANAGER_ADDRESS}
GYE_STAKING_ADDRESS=${LIVE.GYE_STAKING_ADDRESS}
MOIGYE_SBT_ADDRESS=${LIVE.MOIGYE_SBT_ADDRESS}

# ── Spoke Chain Contracts (Ethereum Sepolia) ──────────────────
MOIGYE_USD_ADDRESS=${LIVE.MOIGYE_USD_ADDRESS}
# TODO: Run 'node scripts/deploy_vault_only.mjs' and paste the
#       resulting vault address here:
MOIGYE_VAULT_ADDRESS=""

# ── Frontend / Auth ───────────────────────────────────────────
NEXT_PUBLIC_PRIVY_APP_ID=""
NEXT_PUBLIC_SUPABASE_URL=""
NEXT_PUBLIC_SUPABASE_ANON_KEY=""

# ── Block Explorer Verification ───────────────────────────────
# Optional: required only for 'npx hardhat verify'
ETHERSCAN_API_KEY=""
`;

// ─── Write .env ────────────────────────────────────────────────────────────
if (existsSync(ENV_PATH)) {
    const backup = ENV_PATH + ".backup";
    writeFileSync(backup, readFileSync(ENV_PATH));
    console.log(`ℹ️  Existing .env backed up to .env.backup`);
}

writeFileSync(ENV_PATH, ENV_CONTENT, "utf8");
console.log(`✅  .env written to: ${ENV_PATH}`);
console.log("\n📋  Pre-filled live addresses:");
for (const [k, v] of Object.entries(LIVE)) {
    console.log(`   ${k}=${v}`);
}
console.log("\n⚠️  Still required from you:");
console.log("   PRIVATE_KEY, SEPOLIA_RPC_URL, NEXT_PUBLIC_PRIVY_APP_ID");
console.log("   NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_ANON_KEY");
console.log("   MOIGYE_VAULT_ADDRESS  ← run deploy_vault_only.mjs first");
